### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [olliecoleman/alloy#6]
Followed the instructions on the website, installed Glide and then ran and got this

Js-iMac:alloy jmhowitt$ go install
main.go:6:2: cannot find package "github.com/olliecoleman/alloy/app/services" in any of:
	/Users/jmhowitt/go/src/alloy/vendor/github.com/olliecoleman/alloy/app/services (vendor tree)
	/usr/local/go/src/github.com/olliecoleman/alloy/app/services (from $GOROOT)
	/Users/jmhowitt/go/src/github.com/olliecoleman/alloy/app/services (from $GOPATH)
main.go:7:2: cannot find package "github.com/olliecoleman/alloy/app/views" in any of:
	/Users/jmhowitt/go/src/alloy/vendor/github.com/olliecoleman/alloy/app/views (vendor tree)
	/usr/local/go/src/github.com/olliecoleman/alloy/app/views (from $GOROOT)
	/Users/jmhowitt/go/src/github.com/olliecoleman/alloy/app/views (from $GOPATH)
main.go:8:2: cannot find package "github.com/olliecoleman/alloy/cmd" in any of:
	/Users/jmhowitt/go/src/alloy/vendor/github.com/olliecoleman/alloy/cmd (vendor tree)
	/usr/local/go/src/github.com/olliecoleman/alloy/cmd (from $GOROOT)
	/Users/jmhowitt/go/src/github.com/olliecoleman/alloy/cmd (from $GOPATH)
Js-iMac:alloy jmhowitt$ alloy dev

**Comment by rootsongjc** [comment]
You should use `glide install` to install the dependencies first.

**Comment by ghost** [comment]
This is what i did
n.b. i had to install glide seperately which is not in the HowTo

$ cd /Users/jmhowitt/go/src -- into my go src directory
$ git clone https://github.com/olliecoleman/alloy -- get the repo
$ cd alloy -- got into the directory
$ glide install -- run glide but it is not there
$ curl https://glide.sh/get | sh -- get glide
$ glide install -- install glide
$ npm install -- install npm
$ go install -- try to create the project and get all the errors
$ alloy dev -- falls over of course

**Comment by sahajre** [comment]
Same `go install` issue for me as well. Using MacOS Sierra 10.12.6.

**Comment by rootsongjc** [comment]
@sahajRe I use MacOS Sierra 10.12.6 too but not encounter this error, I think it have no relation with your OS.
Did you clone this project to `$GOPATH/src/github.com/olliecoleman/alloy` directory?

**Comment by ghost** [comment]
OK installed in "$GOPATH/src/github.com/olliecoleman/alloy" so i must have missed that instruction in the documentation.

so now it works up to "alloy dev" where it tells me there is no such command.

**Comment by rootsongjc** [comment]
Have in run `go install` and put the binary file `$GOPATH/bin/alloy` to you `$PATH` such as `/usr/local/bin`?

**Comment by ghost** [comment]
Hmm getting complicated and all of this missing in the installation instructions, i think i will just delete it and get on with something else.

**Comment by sahajre** [comment]
Thanks @rootsongjc. Cloning `alloy` in `$GOPATH/src/github.com/olliecoleman/` worked.
